# It contains all the configs required in the project

# Source of the location from where we getting the data

#We define the source location of the data, local directory where we store the downloanded data(source data) and the filename in 
#Dictionary format
data:
  source_url: "https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_5340.zip"
  local_dir : data
  data_file : data.zip